name: Go CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Go project
      - uses: actions/checkout@v4
        with:
          repository: arcology-network/eu
          path: eu

      # 2. Checkout Solidity project
      - uses: actions/checkout@v4
        with:
          repository: arcology-network/concurrent
          path: concurrent
          # token: ${{ secrets.GITHUB_TOKEN }} # If the repository is private, a token is required

      # 3. Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 4. Install Go dependencies
      - run: go mod tidy
        working-directory: ./eu

      # 5. Run Go tests
      - run: go test ./... -v
        working-directory: ./eu